# Generated by Django 6.1 on 2026-08-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='ammount',
            new_name='amount',
        ),
    ]
